-- Skill List Table
CREATE TABLE Anicoboard_SkillList (
	sId varchar(10),
	projectName VARCHAR2(200),
	StartDate DATE DEFAULT CURRENT_TIMESTAMP,
	EndDate DATE DEFAULT CURRENT_TIMESTAMP,
	customer VARCHAR2(100),
	task VARCHAR2(50),
	os VARCHAR2(50),
	skill_language VARCHAR2(100),
	dbms VARCHAR2(100),
	dev_tool VARCHAR2(100),
	stackList VARCHAR2(300),
	create_date DATE DEFAULT CURRENT_TIMESTAMP,
	create_user VARCHAR2(100) ,
	modify_date DATE DEFAULT CURRENT_TIMESTAMP,
	modify_user VARCHAR2(100) ,
	PRIMARY KEY (sId)
);

--Member Table
CREATE TABLE Anicoboard_Member (
	Id varchar(10),
	eMail VARCHAR2(100),
	passWord VARCHAR2(200),
	userName Varchar2(100),
	create_date DATE DEFAULT CURRENT_TIMESTAMP,
	create_user VARCHAR2(100) ,
	modify_date DATE DEFAULT CURRENT_TIMESTAMP,
	modify_user VARCHAR2(100) ,
	
	PRIMARY KEY (Id)
);

-- SEQ_SKILLLIST_SId 생성
CREATE SEQUENCE SEQ_SKILLLIST_SId
START WITH 1
INCREMENT BY 1
CACHE 20;

-- SEQ_Member_Id 생성
CREATE SEQUENCE SEQ_Member_Id
START WITH 1
INCREMENT BY 1
CACHE 20;

-- 시퀀스 생성 확인
SELECT SEQ_SKILLLIST_SID.NEXTVAL FROM DUAL;
SELECT SEQ_SKILLLIST_SID.CURRVAL FROM DUAL;

-- insert ANicoBoard_SkillList
INSERT INTO ANICOBOARD_SKILLLIST
(SID, PROJECTNAME, STARTDATE, ENDDATE, CUSTOMER, TASK, OS, SKILLLANGUAGE, DBMS, DEVTOOL, STACKLIST, CREATE_DATE, CREATE_USER, MODIFY_DATE, MODIFY_USER)
VALUES
(SEQ_SKILLLIST_SID.NEXTVAL, 'NextPlant 개발', TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'YYYYMMDD'), 'Miracom-inc', '개발', 'Windows/NT', 'Java/JSP', 'SQL Server/PostgreSQL', 'Eclipse/Visual Studio Code', 'Spring[Mes Framework], JQuery, React Library, Gradle', CURRENT_TIMESTAMP, 'leos', CURRENT_TIMESTAMP, 'leos')
;

-- insert Member Table
INSERT INTO ANICOBOARD_MEMBER
(ID, EMAIL, PASSWORD, USERNAME, CREATE_DATE, CREATE_USER, MODIFY_DATE, MODIFY_USER)
VALUES
(SEQ_MEMBER_ID.NEXTVAL, 'highwind26@gmail.com', 'Stonker1220!', 'Leos', CURRENT_TIMESTAMP, 'leos', CURRENT_TIMESTAMP, 'leos')
;

-- select skill_list
SELECT 
	SID
	, PROJECTNAME
	, TO_CHAR(STARTDATE, 'yyyy-MM-dd') AS STARTDATE
	, TO_CHAR(ENDDATE, 'yyyy-MM-dd') AS ENDDATE
	, CUSTOMER
	, TASK
	, OS
	, SKILLLANGUAGE
	, DBMS
	, DEVTOOL
	, STACKLIST
	, CREATE_DATE
	, CREATE_USER
	, MODIFY_DATE
	, MODIFY_USER
FROM ANICOBOARD_SKILLLIST
ORDER BY SID
;

-- select member
SELECT * 
FROM ANICOBOARD_MEMBER;
