-- Skill List Table
CREATE TABLE Anicoboard_SkillList (
	sId varchar(10),
	projectName VARCHAR2(200),
	StartDate DATE DEFAULT CURRENT_TIMESTAMP,
	EndDate DATE DEFAULT CURRENT_TIMESTAMP,
	customer VARCHAR2(100),
	task VARCHAR2(50),
	os VARCHAR2(50),
	skill_language VARCHAR2(100),
	dbms VARCHAR2(100),
	dev_tool VARCHAR2(100),
	stackList VARCHAR2(300),
	create_date DATE DEFAULT CURRENT_TIMESTAMP,
	create_user VARCHAR2(100) ,
	modify_date DATE DEFAULT CURRENT_TIMESTAMP,
	modify_user VARCHAR2(100) ,
	PRIMARY KEY (sId)
);



  CREATE TABLE "LEOS"."ANICOBOARD_SKILLLIST" 
   (	"SID" VARCHAR2(10), 
	"PROJECTNAME" VARCHAR2(200), 
	"STARTDATE" VARCHAR2(8) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD'), 
	"ENDDATE" VARCHAR2(8) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD'), 
	"CUSTOMER" VARCHAR2(100), 
	"TASK" VARCHAR2(50), 
	"OS" VARCHAR2(50), 
	"SKILLLANGUAGE" VARCHAR2(100), 
	"DBMS" VARCHAR2(100), 
	"DEVTOOL" VARCHAR2(100), 
	"STACKLIST" VARCHAR2(300), 
	"CREATE_DATE" DATE DEFAULT CURRENT_TIMESTAMP, 
	"CREATE_USER" VARCHAR2(100), 
	"MODIFY_DATE" DATE DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_USER" VARCHAR2(100), 
	 PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--Member Table
CREATE TABLE Anicoboard_Member (
	Id varchar(10),
	eMail VARCHAR2(100),
	passWord VARCHAR2(200),
	userName Varchar2(100),
	create_date DATE DEFAULT CURRENT_TIMESTAMP,
	create_user VARCHAR2(100) ,
	modify_date DATE DEFAULT CURRENT_TIMESTAMP,
	modify_user VARCHAR2(100) ,
	
	PRIMARY KEY (Id)
);

-- SEQ_SKILLLIST_SId 생성
CREATE SEQUENCE SEQ_SKILLLIST_SId
START WITH 1
INCREMENT BY 1
CACHE 20;

-- SEQ_Member_Id 생성
CREATE SEQUENCE SEQ_Member_Id
START WITH 1
INCREMENT BY 1
CACHE 20;

-- 시퀀스 생성 확인
SELECT SEQ_SKILLLIST_SID.NEXTVAL FROM DUAL;
SELECT SEQ_SKILLLIST_SID.CURRVAL FROM DUAL;

-- insert ANicoBoard_SkillList
INSERT INTO ANICOBOARD_SKILLLIST
(SID, PROJECTNAME, STARTDATE, ENDDATE, CUSTOMER, TASK, OS, SKILL_LANGUAGE, DBMS, DEV_TOOL, STACKLIST, CREATE_DATE, CREATE_USER, MODIFY_DATE, MODIFY_USER)
VALUES
(SEQ_SKILLLIST_SID.NEXTVAL, 'PROJECTNAME', TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'YYYYMMDD'), 'CUSTOMER', 'TASK', 'windows server', 'Java/JSP', 'Oracle 11g', 'Eclipse', 'Spring, MyBATIS, Maven', CURRENT_TIMESTAMP, 'leos', CURRENT_TIMESTAMP, 'leos')
;

-- insert Member Table
INSERT INTO ANICOBOARD_MEMBER
(ID, EMAIL, PASSWORD, USERNAME, CREATE_DATE, CREATE_USER, MODIFY_DATE, MODIFY_USER)
VALUES
(SEQ_MEMBER_ID.NEXTVAL, 'highwind26@gmail.com', 'Stonker1220!', 'Leos', CURRENT_TIMESTAMP, 'leos', CURRENT_TIMESTAMP, 'leos')
;

-- select skill_list
SELECT * 
FROM ANICOBOARD_SKILLLIST;

-- select member
SELECT * 
FROM ANICOBOARD_MEMBER;

SELECT
	SID    
	, PROJECTNAME    
	, SUBSTR(STARTDATE,0,4) || '-' || SUBSTR(STARTDATE,5,2) || '-' || SUBSTR(STARTDATE,7,2) AS STARTDATE  
	, SUBSTR(ENDDATE,0,4) || '-' || SUBSTR(ENDDATE,5,2) || '-' || SUBSTR(ENDDATE,7,2) AS ENDDATE  
	, CUSTOMER    
	, TASK    
	, OS    
	, SKILLLANGUAGE    
	, DBMS    
	, DEVTOOL    
	, STACKLIST    
	, CREATE_DATE    
	, CREATE_USER    
	, MODIFY_DATE    
	, MODIFY_USER   
FROM ANICOBOARD_SKILLLIST   
ORDER BY SID
;
